apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Bear
    patch: |
      - op: replace
        path: /spec/HEAD
        value: blue
